 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Klinik;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class dokter extends javax.swing.JFrame {

    /**
     * Creates new form user
     */
    public dokter() {
        initComponents();
        KosongForm();
        TampilData();
    }
     public void KosongForm(){
        txtKodeD.setEditable(true);
        txtKodeD.setText(null);
        txtNamaD.setText(null);
        cmbJkD.setSelectedItem(this);
        txtAlD.setText(null);
        txtKotaD.setText(null);
        txtTelpD.setText(null);
    }
    
    public void TampilData(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("Kode Dokter");
        model.addColumn("Nama Dokter");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Alamat");
        model.addColumn("Kota");
        model.addColumn("No Telepon");
        
        try{
            int no=1;
            String sql="SELECT * FROM dokter";
            java.sql.Connection conn=(Connection)Konfig.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            
            while(res.next()){
                model.addRow(new Object[]{
                    no++,
                    res.getString(1),
                    res.getString(2),
                    res.getString(3),
                    res.getString(4),
                    res.getString(5),
                    res.getString(6)});
            }
            jTable1.setModel(model);
            
        } catch(SQLException e){
            System.out.println("Error "+e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnKeluar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblKodeD = new javax.swing.JLabel();
        lblNamaD = new javax.swing.JLabel();
        lblJkD = new javax.swing.JLabel();
        lblAlD = new javax.swing.JLabel();
        lblKotaD = new javax.swing.JLabel();
        lblTelpD = new javax.swing.JLabel();
        cmbJkD = new javax.swing.JComboBox<>();
        txtNamaD = new javax.swing.JTextField();
        txtKodeD = new javax.swing.JTextField();
        txtAlD = new javax.swing.JTextField();
        txtKotaD = new javax.swing.JTextField();
        txtTelpD = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnTampil = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(135, 206, 235));

        jPanel3.setBackground(new java.awt.Color(254, 228, 225));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 551, 175));

        btnKeluar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Klinik/icons8-export-40.png"))); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.setIconTextGap(10);
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        jPanel3.add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 131, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Klinik/cici.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-12, 0, 740, 190));

        jPanel4.setBackground(new java.awt.Color(254, 228, 225));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblKodeD.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblKodeD.setText("Kode Dokter");
        jPanel4.add(lblKodeD, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 99, 100, 40));

        lblNamaD.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNamaD.setText("Nama");
        jPanel4.add(lblNamaD, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 147, 100, 40));

        lblJkD.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblJkD.setText("Jenis Kelamin");
        jPanel4.add(lblJkD, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 196, 100, 40));

        lblAlD.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAlD.setText("Alamat");
        jPanel4.add(lblAlD, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 299, 100, 40));

        lblKotaD.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblKotaD.setText("Kota");
        jPanel4.add(lblKotaD, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 247, 100, 40));

        lblTelpD.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTelpD.setText("Telepon");
        jPanel4.add(lblTelpD, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 350, 100, 40));

        cmbJkD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilihan", "Perempuan", "Laki Laki" }));
        jPanel4.add(cmbJkD, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 206, 400, -1));
        jPanel4.add(txtNamaD, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 157, 400, -1));
        jPanel4.add(txtKodeD, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 109, 400, -1));
        jPanel4.add(txtAlD, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 309, 400, -1));

        txtKotaD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKotaDActionPerformed(evt);
            }
        });
        jPanel4.add(txtKotaD, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 257, 400, -1));

        txtTelpD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelpDActionPerformed(evt);
            }
        });
        jPanel4.add(txtTelpD, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 360, 400, -1));

        jLabel1.setFont(new java.awt.Font("Tekton Pro Ext", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Data Dokter");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 21, 730, 71));

        btnSimpan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Klinik/icons8-save-30.png"))); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.setIconTextGap(10);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel4.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 402, 127, 49));

        btnTampil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTampil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Klinik/icons8-view-40 (2).png"))); // NOI18N
        btnTampil.setText("Tampil");
        btnTampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilActionPerformed(evt);
            }
        });
        jPanel4.add(btnTampil, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 402, -1, -1));

        btnEdit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Klinik/icons8-edit-35.png"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.setIconTextGap(10);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel4.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 146, 121, -1));

        btnBatal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Klinik/icons8-cancel-40.png"))); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        jPanel4.add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 346, 121, -1));

        btnHapus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Klinik/icons8-delete-bin-40.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.setIconTextGap(10);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel4.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 243, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Klinik/cici.png"))); // NOI18N
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 730, 460));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtKotaDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKotaDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKotaDActionPerformed

    private void txtTelpDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelpDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelpDActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        try{
            String sql="INSERT INTO dokter VALUES('"+txtKodeD.getText()+"',"
                    + "'"+txtNamaD.getText()+"',"
                    + "'"+cmbJkD.getSelectedItem()+"',"
                    + "'"+txtAlD.getText()+"',"
                    + "'"+txtKotaD.getText()+"',"
                    + "'"+txtTelpD.getText()+"')";
            
            java.sql.Connection conn=(Connection)Konfig.configDB();
            java.sql.PreparedStatement pstm=conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Simpan Data Baru Berhasil");
            TampilData();
            KosongForm();
            
        } catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnTampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilActionPerformed
        // TODO add your handling code here:
        KosongForm();
    }//GEN-LAST:event_btnTampilActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        try{
            String sql="UPDATE dokter SET Kode_Dokter='"+txtKodeD.getText()+"',"
                    + "Nama_Dokter='"+txtNamaD.getText()+"',"
                    + "Jenis_Kelamin='"+cmbJkD.getSelectedItem()+"',"
                    + "Alamat='"+txtAlD.getText()+"',"
                    + "Kota='"+txtKotaD.getText()+"',"
                    + "Telepon='"+txtTelpD.getText()+"' WHERE Kode_Dokter='"+txtKodeD.getText()+"'";
            
            java.sql.Connection conn=(Connection)Konfig.configDB();
            java.sql.PreparedStatement pstm=conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Update Data Berhasil");
            TampilData();
            KosongForm();
            
        } catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
         try{
            String sql="DELETE FROM dokter WHERE Kode_Dokter='"+txtKodeD.getText()+"'";
        
            java.sql.Connection conn=(Connection)Konfig.configDB();
            java.sql.PreparedStatement pstm=conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Hapus Data Berhasil");
            TampilData();
            KosongForm();
            
        } catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
         KosongForm();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         txtKodeD.setEditable(false);
        
        int baris=jTable1.rowAtPoint(evt.getPoint());
        String kode=jTable1.getValueAt(baris, 1).toString();
        txtKodeD.setText(kode);
        String nama=jTable1.getValueAt(baris, 2).toString();
        txtNamaD.setText(nama);
        String jk=jTable1.getValueAt(baris, 3).toString();
        cmbJkD.setSelectedItem(jk);
        String alamat=jTable1.getValueAt(baris, 4).toString();
        txtAlD.setText(alamat);
        String kota=jTable1.getValueAt(baris, 5).toString();
        txtKotaD.setText(kota);
        String telp=jTable1.getValueAt(baris, 6).toString();
        txtTelpD.setText(telp);
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dokter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTampil;
    private javax.swing.JComboBox<String> cmbJkD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAlD;
    private javax.swing.JLabel lblJkD;
    private javax.swing.JLabel lblKodeD;
    private javax.swing.JLabel lblKotaD;
    private javax.swing.JLabel lblNamaD;
    private javax.swing.JLabel lblTelpD;
    private javax.swing.JTextField txtAlD;
    private javax.swing.JTextField txtKodeD;
    private javax.swing.JTextField txtKotaD;
    private javax.swing.JTextField txtNamaD;
    private javax.swing.JTextField txtTelpD;
    // End of variables declaration//GEN-END:variables
}
