/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Klinik;

import java.awt.HeadlessException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.*;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author LENOVO
 */
public class pemeriksaan extends javax.swing.JFrame {

    /**
     * Creates new form pemeriksaan
     */
    public pemeriksaan() {
        initComponents();
        KosongForm();
        TampilData();
        combo_dokter();
        combo_pasien();
    }
    
    public void KosongForm(){
        txtKode.setEditable(true);
        txtKode.setText(null);
        comboKd.setSelectedItem(this);
        txtNamaD.setText(null);
        comboKp.setSelectedItem(this);
        txtNamaP.setText(null);
        txtDiagnosa.setText(null);
        tgl.setDateFormatString(null);
    }
    
    public void TampilData(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("Kode Pemeriksaan");
        model.addColumn("Kode Dokter");
        model.addColumn("Nama Dokter");
        model.addColumn("Kode Pasien");
        model.addColumn("Nama Pasien");
        model.addColumn("Diagnosa");
        model.addColumn("Tanggal Periksa");
        
        try{
            int no=1;
            String sql="SELECT * FROM pemeriksaan";
            java.sql.Connection conn=(Connection)Konfig.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            
            while(res.next()){
                model.addRow(new Object[]{
                    no++,
                    res.getString(1),
                    res.getString(2),
                    res.getString(3),
                    res.getString(4),
                    res.getString(5),
                    res.getString(6),
                    res.getDate(7)});
            }
            jTable1.setModel(model);
            
        } catch(SQLException e){
            System.out.println("Error "+e.getMessage());
        }
    }

     public void combo_dokter(){
        try{
            String sql="SELECT * FROM dokter";
            java.sql.Connection conn=(Connection)Konfig.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            java.sql.ResultSet rs=pst.executeQuery(sql);
            
            while(rs.next()){
                comboKd.addItem(rs.getString("Kode_Dokter"));
            }
            rs.last();
            int jumlahdata = rs.getRow();
            rs.first();
            
        } catch(SQLException e){
            
        }
    }
    
    public void combo_pasien(){
        try{
            String sql="SELECT * FROM pasien";
            java.sql.Connection conn=(Connection)Konfig.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            java.sql.ResultSet rs=pst.executeQuery(sql);
            
            while(rs.next()){
                comboKp.addItem(rs.getString("Kode_Pasien"));
            }
            rs.last();
            int jumlah = rs.getRow();
            rs.first();
            
        } catch(SQLException e){
            
        }
    }
    
    public void tanggal_pemeriksaan(){
        try{
            String sql="SELECT * FROM pemeriksaan where Kode_Pemeriksaan='"+txtKode.getText()+"'";
            java.sql.Connection conn=(Connection)Konfig.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                tgl.setDate(res.getDate("Tanggal_Pemeriksaan"));
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnKeluar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnCetak = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtKode = new javax.swing.JTextField();
        txtNamaD = new javax.swing.JTextField();
        txtNamaP = new javax.swing.JTextField();
        txtDiagnosa = new javax.swing.JTextField();
        btnCariD = new javax.swing.JButton();
        btnCariP = new javax.swing.JButton();
        comboKd = new javax.swing.JComboBox<>();
        comboKp = new javax.swing.JComboBox<>();
        tgl = new com.toedter.calendar.JDateChooser();
        btnBatal = new javax.swing.JButton();
        btnTampil = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setBackground(new java.awt.Color(135, 206, 235));

        jPanel2.setBackground(new java.awt.Color(254, 228, 225));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 575, 220));

        btnKeluar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Klinik/icons8-export-40.png"))); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        jPanel2.add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 177, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Klinik/cici.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-9, -4, 790, 260));

        jPanel3.setBackground(new java.awt.Color(254, 228, 225));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCetak.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Klinik/icons8-print-40.png"))); // NOI18N
        btnCetak.setText("Cetak");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });
        jPanel3.add(btnCetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 450, 120, -1));

        jLabel9.setFont(new java.awt.Font("Tekton Pro Ext", 1, 48)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Tabel Data Pemeriksaan");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 98));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Kode Pemeriksaan");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 118, 150, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Kode Dokter");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 165, 150, 41));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nama Dokter");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 213, 150, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Kode Pasien");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 264, 150, 41));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Nama Pasien");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 316, 150, 42));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Diagnosa");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 369, 150, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Tanggal Pemeriksaan");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 421, 150, 40));
        jPanel3.add(txtKode, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 128, 305, -1));
        jPanel3.add(txtNamaD, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 223, 305, -1));
        jPanel3.add(txtNamaP, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 327, 305, -1));
        jPanel3.add(txtDiagnosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 379, 305, -1));

        btnCariD.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCariD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Klinik/icons8-search-30.png"))); // NOI18N
        btnCariD.setText("Cari");
        btnCariD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariDActionPerformed(evt);
            }
        });
        jPanel3.add(btnCariD, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 170, -1, 30));

        btnCariP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCariP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Klinik/icons8-search-30.png"))); // NOI18N
        btnCariP.setText("Cari");
        btnCariP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariPActionPerformed(evt);
            }
        });
        jPanel3.add(btnCariP, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 269, -1, 30));

        comboKd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilihan" }));
        jPanel3.add(comboKd, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 175, 305, -1));

        comboKp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilihan" }));
        jPanel3.add(comboKp, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 274, 304, -1));
        jPanel3.add(tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 439, 305, -1));

        btnBatal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Klinik/icons8-cancel-40.png"))); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        jPanel3.add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, 127, -1));

        btnTampil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTampil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Klinik/icons8-view-40 (2).png"))); // NOI18N
        btnTampil.setText("Tampil");
        btnTampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilActionPerformed(evt);
            }
        });
        jPanel3.add(btnTampil, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 492, -1, -1));

        btnEdit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Klinik/icons8-edit-35.png"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel3.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 152, 127, 49));

        btnHapus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Klinik/icons8-delete-bin-40.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.setIconTextGap(10);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel3.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 365, -1, -1));

        btnSimpan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Klinik/icons8-save-30.png"))); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.setIconTextGap(10);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel3.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 492, 134, 49));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Klinik/cici.png"))); // NOI18N
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 790, 560));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 834, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilActionPerformed
        // TODO add your handling code here:
         KosongForm();
    }//GEN-LAST:event_btnTampilActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
           dispose(); 
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        String tampilan = "yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String tanggal = String.valueOf(fm.format(tgl.getDate()));
        try{
            String sql="INSERT INTO pemeriksaan VALUES('"+txtKode.getText()+"',"
                    + "'"+comboKd.getSelectedItem()+"',"
                    + "'"+txtNamaD.getText()+"',"
                    + "'"+comboKp.getSelectedItem()+"',"
                    + "'"+txtNamaP.getText()+"',"
                    + "'"+txtDiagnosa.getText()+"',"
                    + "'"+tanggal+"')";
            
            java.sql.Connection conn=(Connection)Konfig.configDB();
            java.sql.PreparedStatement pstm=conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Simpan Data Baru Berhasil");
            TampilData();
            KosongForm();
            combo_dokter();
            combo_pasien();
            
        } catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         txtKode.setEditable(false);
        
        int baris=jTable1.rowAtPoint(evt.getPoint());
        String kode=jTable1.getValueAt(baris, 1).toString();
        txtKode.setText(kode);
        String kodeD=jTable1.getValueAt(baris, 2).toString();
        comboKd.setSelectedItem(kodeD);
        String namaD=jTable1.getValueAt(baris, 3).toString();
        txtNamaD.setText(namaD);
        String kodeP=jTable1.getValueAt(baris, 4).toString();
        comboKp.setSelectedItem(kodeP);
        String namaP=jTable1.getValueAt(baris, 5).toString();
        txtNamaP.setText(namaP);
        String diagnosa=jTable1.getValueAt(baris, 6).toString();
        txtDiagnosa.setText(diagnosa);
        tanggal_pemeriksaan();
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        KosongForm();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
         try{
            String sql="DELETE FROM pemeriksaan WHERE Kode_Pemeriksaan='"+txtKode.getText()+"'";
        
            java.sql.Connection conn=(Connection)Konfig.configDB();
            java.sql.PreparedStatement pstm=conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Hapus Data Berhasil");
            TampilData();
            KosongForm();
            
        } catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnCariDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariDActionPerformed
        // TODO add your handling code here:
        String kodedokter = (String) comboKd.getSelectedItem();
        try{
            String sql="SELECT * FROM dokter WHERE Kode_Dokter like '"+kodedokter+"'";
            java.sql.Connection conn=(Connection)Konfig.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            if (res.next()){
                txtNamaD.setText(res.getString(2));
                JOptionPane.showMessageDialog(null, "Data ditemukan","Insert Data",JOptionPane.INFORMATION_MESSAGE);
            } else{
                JOptionPane.showMessageDialog(null, "Data tidak ditemukan ","Insert Data",JOptionPane.INFORMATION_MESSAGE);
            }
        
        } catch(SQLException e){
            System.out.println("Error "+e.getMessage());
        }
    }//GEN-LAST:event_btnCariDActionPerformed

    private void btnCariPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariPActionPerformed
        // TODO add your handling code here:
         String kodepasien = (String) comboKp.getSelectedItem();
        try{
            String sql="SELECT * FROM pasien WHERE Kode_Pasien like '"+kodepasien+"'";
            java.sql.Connection conn=(Connection)Konfig.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            if (res.next()){
                txtNamaP.setText(res.getString(2));
                JOptionPane.showMessageDialog(null, "Data ditemukan","Insert Data",JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null, "Data tidak ditemukan ","Insert Data",JOptionPane.INFORMATION_MESSAGE);
            }
        
        }catch(SQLException e){
            System.out.println("Error "+e.getMessage());
        }
    }//GEN-LAST:event_btnCariPActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        String tampilan = "yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String tanggal = String.valueOf(fm.format(tgl.getDate()));
        try{
            String sql="UPDATE pemeriksaan SET Kode_Pemeriksaan='"+txtKode.getText()+"',"
                    + "Kode_Dokter='"+comboKd.getSelectedItem()+"',"
                    + "Nama_Dokter='"+txtNamaD.getText()+"',"
                    + "Kode_Pasien='"+comboKp.getSelectedItem()+"',"
                    + "Nama_Pasien='"+txtNamaP.getText()+"',"
                    + "Diagnosa='"+txtDiagnosa.getText()+"',"
                    + "Tanggal_Pemeriksaan='"+tanggal+"' WHERE Kode_Pemeriksaan='"+txtKode.getText()+"'";
            
            java.sql.Connection conn=(Connection)Konfig.configDB();
            java.sql.PreparedStatement pstm=conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Update Data Berhasil");
            TampilData();
            KosongForm();
            combo_dokter();
            combo_pasien();
            
        } catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
        try{
            InputStream is = pemeriksaan.class.getResourceAsStream("pemeriksaan.jasper");
            JasperPrint jsPrint = JasperFillManager.fillReport(is, null, Konfig.configDB());
            JasperViewer.viewReport(jsPrint, false);
            
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "gagal mencetak laporan karena :"
                + e.getMessage(), "cetak laporan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pemeriksaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pemeriksaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pemeriksaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pemeriksaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pemeriksaan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCariD;
    private javax.swing.JButton btnCariP;
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTampil;
    private javax.swing.JComboBox<String> comboKd;
    private javax.swing.JComboBox<String> comboKp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.Panel panel1;
    private com.toedter.calendar.JDateChooser tgl;
    private javax.swing.JTextField txtDiagnosa;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtNamaD;
    private javax.swing.JTextField txtNamaP;
    // End of variables declaration//GEN-END:variables
}
